name: Docker

# action execution section
on:
  schedule:
    - cron: '24 7 1 * *'
  workflow_dispatch: # adding the workflow_dispatch so it can be triggered manually
    inputs:
      uselessinput:
        description: 'What text do you want to print?'
        required: false
        default: 'Periodically printing passages'
  # push:
    # branches: [ "main" ]
    # Publish semver tags as releases.
    # tags: [ 'v*.*.*' ]
  #pull_request:
   # branches: [ "main" ]
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Get current date
#         id: date
#         run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          #tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:latest,${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ steps.date.outputs.date }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:latest,${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ env.date }}

#   scan:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3
#       - name: Scan with Mondoo
#         uses: mondoohq/actions/docker-image@main
#         with:
#           service-account-credentials: ${{ secrets.MONDOO_SERVICE_ACCOUNT }}
#           image: ubuntu:22.04
